name: Actualizador compras

on:

  # Se ejecuta autom치ticamente con este horario
  schedule:
    # Horario UTC. Espa침a es UTC+1 (Invierno) / UTC+2 (Verano).
    # Se ejecutar치 a las: 07:10, 10:10, 13:10, 16:10, 19:10 y 22:10 (Hora Espa침a Invierno)
    #- cron: '10 1422 * * *'

  # Te permite ejecutarlo manualmente con un bot칩n si lo necesitas probar ya
  workflow_dispatch:
  
  # --- SOLUCI칍N AL ERROR 403 ---
permissions:
  actions: write
  contents: read
# -----------------------------

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar c칩digo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar librer칤as
      run: |
        python -m pip install --upgrade pip
        # Instalamos las librer칤as que usa tu script
        pip install requests beautifulsoup4 woocommerce lxml

    - name: Ejecutar Script
      env:
        # Aqu칤 inyectamos los secretos que ya creaste
        WP_URL: ${{ secrets.WP_URL }}
        WP_KEY: ${{ secrets.WP_KEY }}
        WP_SECRET: ${{ secrets.WP_SECRET }}
      run: python compras.py

    # --- LIMPIEZA AUTOM츼TICA ---
    - name: 游빛 Borrar historiales antiguos
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 7       # Mantiene solo 1 semana de historial
        keep_minimum_runs: 6 # Guarda m칤nimo las 칰ltimas 6 ejecuciones por seguridad
